apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-app-v1
  labels:
    app: canary-demo-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-demo-app
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: canary-demo-app
        version: v1
    spec:
      containers:
      - name: canary-demo-app
        image: ${DOCKER_HUB_REPO}:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"



    - port: 80
      targetPort: 3000
  selector:
    app: canary-demo-app
    version: v1
