apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-app-v1
  labels:
    app: canary-demo-app
    version: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: canary-demo-app
      version: v1
  template:
    metadata:
      labels:
        app: canary-demo-app
        version: v1
    spec:
      containers:
      - name: canary-demo-app
        image: image_name
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: canary-demo-app-v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: canary-demo-app
    version: v1
