apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-app-v1
  labels:
    app: canary-demo-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-demo-app
      version: v1
  template:
    metadata:
      labels:
        app: canary-demo-app
        version: v1
    spec:
      containers:
      - name: canary-demo-app
        image: your-docker-hub-username/canary-demo-app:v1
        ports:
        - containerPort: 3000
