apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-app-v2
  labels:
    app: canary-demo-app
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-demo-app
      version: v2
  template:
    metadata:
      labels:
        app: canary-demo-app
        version: v2
    spec:
      containers:
      - name: canary-demo-app
        image: image_name
        ports:
        - containerPort: 3000
