apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-app-v2
  labels:
    app: canary-demo-app
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-demo-app
      version: v2
  template:
    metadata:
      labels:
        app: canary-demo-app
        version: v2
    spec:
      containers:
      - name: canary-demo-app
        image: ${DOCKER_HUB_REPO}:${VERSION}
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
