apiVersion: v1
kind: Service
metadata:
  name: canary-demo-app-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: canary-demo-app
