name: Build, Push to Docker Hub, and Deploy to EKS
#on:
  push:
    branches: [ main ]
    paths:
      - 'v1/**'
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_USERNAME }}/nj-app
  AWS_REGION: us-west-1
  EKS_CLUSTER_NAME: k8s-cluster
  VERSION: latest
jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      run: |
        if [ -z "$DOCKER_HUB_REPO" ]; then
          echo "Error: DOCKER_HUB_REPO is empty or not set"
          exit 1
        fi
        echo "Building image: ${DOCKER_HUB_REPO}:${VERSION}"
        docker build -t "${DOCKER_HUB_REPO}:${VERSION}" -f v1/Dockerfile v1
        docker push "${DOCKER_HUB_REPO}:${VERSION}"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
    - name: Deploy to EKS
      run: |
        cd kubernetes
        envsubst < deploymentv1.yaml | kubectl apply -f -
        kubectl apply -f service1.yaml
        kubectl apply -f service.yaml
    - name: Verify deployment
      run: |
        kubectl get deployments
        kubectl get services
        kubectl get pods
