name: Build, Push to Docker Hub, and Deploy to EKS (Canary V2)
on:
  push:
    branches: [ main ]
    paths:
      - 'v2/**'
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_REPO: miran77/nj-app
  AWS_REGION: us-west-1
  EKS_CLUSTER_NAME: k8s-cluster
  VERSION: v2
jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        echo "Building image: ${DOCKER_HUB_REPO}:${VERSION}"
        docker build -t "${DOCKER_HUB_REPO}:${VERSION}" -f v2/Dockerfile v2
        docker push "${DOCKER_HUB_REPO}:${VERSION}"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
    
    - name: Deploy to EKS
      run: |
        sed -i "s|\${DOCKER_HUB_REPO}|${{ env.DOCKER_HUB_REPO }}|g" kubernetes/deploymentv2.yaml
        sed -i "s|\${VERSION}|${{ env.VERSION }}|g" kubernetes/deploymentv2.yaml
        kubectl apply -f kubernetes/deploymentv2.yaml
        kubectl apply -f kubernetes/service-lb.yaml
        
        # Scale v1 and v2 deployments to ensure 50/50 split
        kubectl scale deployment canary-demo-app-v1 --replicas=2
        kubectl scale deployment canary-demo-app-v2 --replicas=2
    
    - name: Verify deployments
      run: |
        kubectl get deployments
        kubectl get pods
        kubectl get services
        kubectl describe service canary-demo-app-lb
