name: Create Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'

env:
  AWS_REGION: us-west-1
  TF_LOG: INFO

jobs:
  terraform:
    name: Create Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
        cd terraform
        terraform init
      
    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt -check

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -out=tfplan
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve tfplan

    - name: Terraform Output
      run: |
        cd terraform
        terraform output
